#multipart:
#  springboot:
#    webmvc:
#      server:
#        enabled: false

spring:
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
#  cloud:
#    azure:
#      appconfiguration:
#        enabled: false
#      active-directory:
#        enabled: false
#        application-type: web-application-and-resource-server
#      keyvault:
#        enabled: false

  graphql:    
    graphiql:
      enabled: true

  main:
    banner-mode: off

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true

server:
  tomcat:
    relaxed-query-chars: "[,]"