spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: 8749bead-2f85-457d-93b7-de53d5f2dd55
        app-id-uri: api://8749bead-2f85-457d-93b7-de53d5f2dd55 
      keyvault:
        enabled: true
        secret:
          property-sources[0]:
            endpoint: https://csm-ms-main-dev.vault.azure.net
  graphql:
    graphiql:
      enabled: true

  main:
    banner-mode: off

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true

server:
  tomcat:
    relaxed-query-chars: "[,]"