spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        app-id-uri: api://${spring.cloud.azure.active-directory.credential.client-id}
  graphql:
    graphiql:
      enabled: true

  main:
    banner-mode: off

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true

server:
  tomcat:
    relaxed-query-chars: "[,]"